[package]
name = "halo2"
version = "0.0.1"
authors = [
    "Sean Bowe <sean@electriccoin.co>",
    "Ying Tong Lai <yingtong@electriccoin.co>",
    "Daira Hopwood <daira@electriccoin.co>",
    "Jack Grigg <jack@electriccoin.co>",
]
edition = "2018"
description = """
Fast proof-carrying data implementation with no trusted setup
"""
license = "TGPPL"
repository = "https://github.com/Electric-Coin-Company/halo2"
documentation = "https://docs.rs/halo2"
readme = "README.md"

# We are not publishing this yet.
publish = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--html-in-header", "katex-header.html"]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "arithmetic"
harness = false

[[bench]]
name = "hashtocurve"
harness = false

[[bench]]
name = "plonk"
harness = false

[dependencies]
backtrace = { version = "0.3", optional = true }
subtle = "2.3"
crossbeam-utils = "0.8"
ff = "0.9"
group = "0.9"
num_cpus = "1.13"
rand = "0.8"
blake2b_simd = "0.5"
lazy_static = "1.4.0"
static_assertions = "1.1.0"

# Temporary workaround for https://github.com/myrrlyn/funty/issues/3
funty = "=1.1.0"

# Developer tooling dependencies
plotters = { version = "0.3.0", optional = true }
tabbycat = { version = "0.1", features = ["attributes"], optional = true }

[features]
dev-graph = ["plotters", "tabbycat"]
gadget-traces = ["backtrace"]
sanity-checks = []

[[example]]
name = "circuit-layout"
required-features = ["dev-graph"]
