[package]
name = "orchard"
version = "0.0.0"
authors = [
    "Sean Bowe <sean@electriccoin.co>",
    "Jack Grigg <jack@electriccoin.co>",
]
edition = "2018"
description = "Sapling on stilts!"
license = "BOSL"
repository = "https://github.com/zcash/orchard"
documentation = "https://docs.rs/orchard"
readme = "README.md"

# We are not publishing this yet.
publish = false

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[dependencies]
aes = "0.6"
bitvec = "0.20"
blake2b_simd = "0.5"
ff = "0.9"
fpe = "0.4"
group = "0.9"
nonempty = "0.6"
subtle = "2.3"

[dependencies.halo2]
git = "https://github.com/zcash/halo2.git"
rev = "b079624ea78b4a07d44cb3c725dd734093577062"

[dependencies.pasta_curves]
git = "https://github.com/zcash/pasta_curves.git"
rev = "0a6b2f6eb5acbe1dabc9e77ed0bcb748cc640196"

[dependencies.reddsa]
git = "https://github.com/str4d/redjubjub.git"
rev = "f8ff124a52d86e122e0705e8e9272f2099fe4c46"

[dev-dependencies]
criterion = "0.3"
hex = "0.4"

[lib]
bench = false

[[bench]]
name = "small"
harness = false
