[package]
name = "halo2"
version = "0.0.1"
authors = [
    "Sean Bowe <sean@electriccoin.co>",
    "Ying Tong Lai <yingtong@electriccoin.co>",
]
edition = "2018"
description = """
Fast proof-carrying data implementation with no trusted setup
"""
license = "TGPPL"
repository = "https://github.com/Electric-Coin-Company/halo2"
documentation = "https://docs.rs/halo2"
readme = "README.md"

# We are not publishing this yet.
publish = false

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "arithmetic"
harness = false

[dependencies]
subtle = "2.2.1"
crossbeam-utils = "0.7"
num_cpus = "1.13"
rand = "0.7"
