[book]
authors = [
    "Jack Grigg",
    "Sean Bowe",
    "Daira Hopwood",
    "Ying Tong Lai",
]
language = "en"
multilingual = false
src = "src"
title = "The halo2 Book"

[preprocessor.katex]
macros = "macros.txt"
renderers = ["html"]

[output.katex]

[output.html]

[output.html.print]
# Disable page break
page-break = false

[output.pdf]
optional = true
display-header-footer = true
header-template = "<span></span>"
footer-template = "<p style='font-size:10px; margin-left: 48%'><span class='pageNumber'></span> / <span class='totalPages'></span></p>"

[output.pdf-outline]
optional = true
like-wkhtmltopdf = false
