name: halo2 book

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
        id: toolchain
      - run: rustup override set "${TOOLCHAIN}"
        shell: sh
        env:
          TOOLCHAIN: ${{steps.toolchain.outputs.name}}

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@adeb05db28a0c0004681db83893d56c0388ea9ea # v1.2.0
        with:
          mdbook-version: '0.4.52'

      - name: Install mdbook-katex and mdbook-pdf
        run: cargo install mdbook-katex mdbook-pdf

      - name: Install mdbook-pdf-outline
        run: pip3 install mdbook-pdf-outline

      - name: Build halo2 book
        run: mdbook build book/

      - name: Build latest rustdocs
        run: >
          cargo doc
          --no-deps
          --workspace
          --all-features
        env:
          RUSTDOCFLAGS: -Z unstable-options --enable-index-page --cfg docsrs --html-in-header ${{ github.workspace }}/halo2_proofs/katex-header.html

      - name: Move latest rustdocs into book
        run: |
          mkdir -p ./book/book/html/rustdoc
          mv ./target/doc ./book/book/html/rustdoc/latest

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book/html

      - name: Upload PDF File to Artifact
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: The_halo2_Book
          path: book/book/pdf-outline/*.pdf
